---
hpc_tuning_sysctl_file: /etc/sysctl.d/99-hpc-tuning.conf
hpc_tuning_sysctl_params:
  - name: net.core.rmem_max
    value: '16777216'
  - name: net.ipv4.tcp_rmem
    value: '4096 87380 16777216'
  - name: net.ipv4.tcp_wmem
    value: '4096 65536 16777216'
  - name: vm.max_map_count
    value: '262144'
