---
nvidia_gpu_enabled: true
nvidia_gpu_install_kernel_headers: true
nvidia_gpu_enable_persistence_mode: true
nvidia_gpu_driver_apt_repo: "ppa:graphics-drivers/ppa"
nvidia_gpu_driver_package: nvidia-headless-535-server
